/**
 *  Nuxt.js配置文件 
 */

module.exports={
    router:{
        linkActiveClass:'active',//路由设置样式，任意路由被激活后，在当前nuxt-link连接中增加class样式，使之高亮
        //自定义路由表规则
        extendRoutes(routes, resolve) {
            console.log(routes)
            //清除Nuxt.js基于pages目录默认生成的路由表规则
            routes.splice(0)
            routes.push(...[
                {
                    path:'/',
                    component:resolve(__dirname,'pages/layout'),
                    children:[
                        {
                            path:'',//默认子路由
                            name:'home',
                            component:resolve(__dirname,'pages/home/')
                        },
                        {
                            path:'/login',
                            name:'login',
                            component:resolve(__dirname,'pages/login/')
                        },
                        {
                            path:'/register',//默认子路由
                            name:'register',
                            component:resolve(__dirname,'pages/login/')
                        },
                        {
                            path:'/profile/:username',
                            name:'profile',
                            component:resolve(__dirname,'pages/profile/')
                        },
                        {
                            path:'/settings',
                            name:'settings',
                            component:resolve(__dirname,'pages/settings/')
                        },
                        {
                            path:'/editor',
                            name:'editor',
                            component:resolve(__dirname,'pages/editor/')
                        },
                        {
                            path:'/article/:slug',//动态路由
                            name:'article',
                            component:resolve(__dirname,'pages/article/')
                        }
                    ]
                }
            ])
          }
    },
    server:{
        host:'0.0.0.0',
        port:3000
    },
    //注册插件
    plugins:[
        '~/plugins/request.js',
        '~/plugins/dayjs.js'
    ]
}